spring.datasource.url=jdbc:mysql://localhost:3306/financity?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=358160

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver